name: Deploy via Envoy

on:
  push:
    branches:
      - trunk

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Install Composer dependencies
        run: composer install

      - name: Install Laravel Envoy
        run: composer global require laravel/envoy

      - name: Setup SSH Keys
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan 107.172.79.23 >> ~/.ssh/known_hosts

      - name: Test SSH connection
        run: ssh -v root@107.172.79.23 -i ~/.ssh/id_rsa

      - name: Deploy via Envoy
        run: ~/.composer/vendor/bin/envoy run deploy
