name: Deploy with Envoy

on:
  workflow_dispatch:
  push:
    branches:
      - trunk

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy with Envoy
        run: envoy run deploy
